modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/MennoMax/astikor-carts/issues"
[[mods]]
modId="astikorcarts"
version="${file.jarVersion}"
displayName="AstikorCarts"
displayURL="https://www.curseforge.com/minecraft/mc-mods/astikorcarts"
# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="examplemod.png"
authors="MennoMax, pau101"
description="This mod adds carts that can be pulled by other entities to the game.\nTo attach an entity, press the \"Action Key\" specified in the controls.\n\nYou might have to add the entity in the config file first."

[[dependencies.astikorcarts]]
    modId = "forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.astikorcarts]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
